FROM registry.erda.cloud/retag/golang:1.17-buster AS builder

WORKDIR /workspace

COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY cmd/ cmd/
COPY go.mod go.mod
COPY go.sum go.sum
RUN GOPROXY=https://goproxy.cn,direct CGO_ENABLED=0 GOOS=linux go build -a -o mylet ./cmd/mylet/

FROM registry.erda.cloud/retag/mysql:8.0.35

RUN microdnf install -y yum
RUN yum reinstall -y glibc glibc-common && \
  yum install -y vim net-tools && \
  yum clean all

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
  echo Asia/Shanghai > /etc/timezone

RUN yum install -y curl && \
  curl -o /tmp/xtrabackup.rpm -L https://erda-project.oss-cn-hangzhou.aliyuncs.com/erda-addons/percona-xtrabackup-80-8.0.35-31.1.el8.$(uname -m).rpm && \
  yum install -y /tmp/xtrabackup.rpm && \
  rm -f /tmp/xtrabackup.rpm && \
  yum clean all 
  
WORKDIR /
COPY --from=builder /workspace/mylet .
VOLUME /mydir
EXPOSE 3306 33080
USER mysql:mysql
ENTRYPOINT []
CMD ["/mylet"]
