FROM registry.erda.cloud/erda-x/golang:1 AS builder

WORKDIR /workspace

COPY cmd/ cmd/
COPY api/ api/
COPY controllers/ controllers/
COPY pkg/ pkg/
COPY go.mod go.mod
COPY go.sum go.sum
RUN CGO_ENABLED=0 go build -a -o myctl ./cmd/myctl/

FROM registry.erda.cloud/erda-x/debian:11

RUN sed -i 's@http://mirrors.163.com@http://mirrors.aliyun.com@g' /etc/apt/sources.list && \
    apt-get update && apt-get install -y curl && apt-get clean

WORKDIR /
COPY --from=builder /workspace/myctl .
EXPOSE 33081
USER dice:dice
ENTRYPOINT []
CMD ["/myctl"]
